# Generated by Django 5.1.1 on 2025-06-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='image',
            field=models.ImageField(default='public_image/items/default_food.jpg', upload_to='public_image/items/actual_items/food'),
        ),
        migrations.AlterField(
            model_name='other_items',
            name='image',
            field=models.ImageField(default='public_image/items/default_image.jpg', upload_to='public_image/items/actual_items/other'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default_profile_pic.jpg', upload_to='profile_pic/personal_images'),
        ),
    ]
