# Generated by Django 5.1.1 on 2025-08-05 14:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_food_items_image_alter_other_items_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='exp_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2030, 8, 4))]),
        ),
    ]
