# Generated by Django 5.1.1 on 2025-09-16 18:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_food_items_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='exp_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2030, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='image',
            field=models.ImageField(default='items/default_food.jpg', upload_to='items/actual_items/food'),
        ),
    ]
