# Generated by Django 5.1.1 on 2025-10-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='number',
        ),
    ]
