# Generated by Django 4.2.16 on 2025-10-28 20:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_food_items_deleted_on_food_items_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_items",
            name="restored",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 10, 27)
                    )
                ],
            ),
        ),
    ]
