# Generated by Django 4.2.16 on 2025-11-05 20:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_alter_food_items_exp_date_shoppingcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2030, 11, 4))
                ],
            ),
        ),
    ]
