# Generated by Django 5.2.8 on 2025-11-23 14:13

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_rename_name_shop_items_item_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 11, 22)
                    )
                ],
            ),
        ),
        migrations.RenameModel(
            old_name="Shopping_List",
            new_name="ShoppingList",
        ),
        migrations.CreateModel(
            name="Shopitems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("food", "Food"), ("other", "Other")], max_length=10
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=512)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchased", models.BooleanField(default=False)),
                (
                    "food_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_entries",
                        to="storage.food_items",
                    ),
                ),
                (
                    "other_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_entries",
                        to="storage.other_items",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="storage.shoppinglist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Shop_items",
        ),
    ]
