# Generated by Django 5.2.8 on 2025-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0015_shopitems_family_shoppinglist_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
