# Generated by Django 5.2.8 on 2025-11-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_shoppinglist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
