# Generated by Django 5.2.8 on 2025-12-21 12:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0017_alter_shoppinglist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 12, 20)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(default="unkown", max_length=512),
        ),
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="storage.family",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
