# Generated by Django 5.2.8 on 2025-12-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "storage",
            "0018_alter_food_items_exp_date_alter_profile_display_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="storage.family",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("admin", "Admin"), ("user", "User")],
                max_length=10,
            ),
        ),
    ]
