# Generated by Django 5.2.8 on 2025-12-21 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0019_alter_profile_display_name_alter_profile_family_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="shoppinglist",
            constraint=models.UniqueConstraint(
                fields=("family", "slug"), name="unique_shoppinglist_slug_per_family"
            ),
        ),
    ]
