# Generated by Django 5.2.8 on 2025-12-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0020_alter_shoppinglist_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="storage.family",
            ),
        ),
    ]
