# Generated by Django 5.2.8 on 2025-12-24 16:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0024_alter_profile_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_items",
            name="price",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 12, 23)
                    )
                ],
            ),
        ),
    ]
