# Generated by Django 5.2.8 on 2025-12-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_food_items_price_alter_food_items_exp_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="other_items",
            name="price",
            field=models.DecimalField(decimal_places=2, default=67, max_digits=10),
            preserve_default=False,
        ),
    ]
