# Generated by Django 5.2.8 on 2025-12-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0026_other_items_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitems",
            name="slug",
            field=models.SlugField(default="slug"),
            preserve_default=False,
        ),
    ]
