# Generated by Django 5.2.8 on 2025-12-26 15:27

import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0027_shopitems_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 12, 25)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="other_items",
            name="image",
            field=models.ImageField(
                default="items/default_image.jpg", upload_to="items/actual_items/other"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopitems",
            constraint=models.UniqueConstraint(
                fields=("family", "slug"), name="unique_shopitem_slug_per_family"
            ),
        ),
    ]
