# Generated by Django 5.2.8 on 2025-12-30 16:57

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0028_alter_food_items_exp_date_alter_other_items_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="font_size",
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name="profile",
            name="letter_spacing",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="light",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2030, 12, 29)
                    )
                ],
            ),
        ),
    ]
