# Generated by Django 5.2.8 on 2026-01-04 15:49

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0029_profile_created_at_profile_font_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_items",
            name="barcode",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2031, 1, 3))
                ],
            ),
        ),
    ]
