# Generated by Django 5.2.8 on 2026-01-24 17:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0030_food_items_barcode_alter_food_items_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2031, 1, 23))
                ],
            ),
        ),
    ]
