# Generated by Django 5.2.8 on 2026-02-01 17:53

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0032_remove_profile_family_remove_profile_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2031, 1, 31))
                ],
            ),
        ),
    ]
