# Generated by Django 5.2.8 on 2026-02-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0033_alter_food_items_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_families",
                to="storage.profile",
            ),
        ),
    ]
