# Generated by Django 5.2.8 on 2026-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0034_alter_family_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("admin", "Admin"), ("user", "User")],
                default="Admin",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
