# Generated by Django 5.2.8 on 2026-02-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0035_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
    ]
