# Generated by Django 5.2.8 on 2026-02-07 18:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0036_remove_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="families",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="storage.family"
            ),
        ),
        migrations.AlterField(
            model_name="food_items",
            name="exp_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2031, 2, 6))
                ],
            ),
        ),
    ]
