# Generated by Django 5.2.8 on 2026-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0038_alter_food_items_exp_date_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(
                default="items/default_meal.jpg", upload_to="items/actual_items/recipes"
            ),
        ),
    ]
