# Generated by Django 5.2.8 on 2026-03-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0039_recipe_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default="food i need food"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
