# Generated by Django 5.2.8 on 2026-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0040_recipe_instructions_alter_recipe_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(default="cake", editable=False, unique=True),
            preserve_default=False,
        ),
    ]
