# Generated by Django 5.2.8 on 2026-03-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0041_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="family",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="storage.family",
            ),
            preserve_default=False,
        ),
    ]
